baseURL = ""
languageCode = "en-us"
title = "AWS Lambda - Serverless"
theme = "ananke"

[params.lambdaComments]
endpoint = "https://jpbhvuyepe.execute-api.us-east-2.amazonaws.com/default/student1005-comments-post"